service: aws-nodejs

provider:
  name: aws
  stage: dev
  region: us-east-1
  iamRoleStatements:
  - Effect: Allow
    Action:
    - dynamodb:Scan
    - dynamodb:PutItem
    - dynamodb:GetItem
    - dynamodb:DeleteItem
    - dynamodb:Query
    - dynamodb:UpdateItem
    Resource:
    - "Fn::Join": ["", ["arn:aws:dynamodb:", {"Ref": "AWS::Region"}, ":", {"Ref": "AWS::AccountId"}, ":table/todo-user*"]]
    - "Fn::Join": ["", ["arn:aws:dynamodb:", {"Ref": "AWS::Region"}, ":", {"Ref": "AWS::AccountId"}, ":table/todo-task*"]]

runtime: nodejs6.10

functions:
  getUsers:
    handler: handler.getUsers
    events:
    - http:
        path: user
        method: get
  postUser:
    handler: handler.postUser
    events:
    - http:
        path: user
        method: post
  getUser:
    handler: handler.getUser
    events:
    - http:
        path: user/{userId}
        method: get
  deleteUser:
    handler: handler.deleteUser
    events:
    - http:
        path: user/{userId}
        method: delete
  getTasks:
    handler: handler.getTasks
    events:
    - http:
        path: user/{userId}/task
        method: get
  postTask:
    handler: handler.postTask
    events:
    - http:
        path: user/{userId}/task
        method: post
  putTask:
    handler: handler.putTask
    events:
    - http:
        path: user/{userId}/task/{taskId}
        method: put
  deleteTask:
    handler: handler.deleteTask
    events:
    - http:
        path: user/{userId}/task/{taskId}
        method: delete
  getTasksByCategory:
    handler: handler.getTasksByCategory
    events:
    - http:
        path: category/{category}/task
        method: get

resources:
  Resources:
    UserTable: 
      Type: "AWS::DynamoDB::Table"
      Properties: 
        AttributeDefinitions: 
        - AttributeName: "uid"
          AttributeType: "S"
        KeySchema: 
        - AttributeName: "uid"
          KeyType: "HASH"
        ProvisionedThroughput: 
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: "todo-user"
    TaskTable: 
      Type: "AWS::DynamoDB::Table"
      Properties: 
        AttributeDefinitions: 
        - AttributeName: "uid"
          AttributeType: "S"
        - AttributeName: "tid"
          AttributeType: "N"
        - AttributeName: "category"
          AttributeType: "S"
        KeySchema: 
        - AttributeName: "uid"
          KeyType: "HASH"
        - AttributeName: "tid"
          KeyType: "RANGE"
        GlobalSecondaryIndexes: 
        - IndexName: "category-index"
          KeySchema: 
          - AttributeName: "category"
            KeyType: "HASH"
          - AttributeName: "tid"
            KeyType: "RANGE"
          Projection: 
            ProjectionType: "ALL"
          ProvisionedThroughput: 
            ReadCapacityUnits: 1
            WriteCapacityUnits: 1
        ProvisionedThroughput: 
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: "todo-task"
